# Configuration API Gateway - Teranga Biz Platform
# À placer dans le dépôt GitHub : configurations-teranga-biz/api-gateway.yml

server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  # Configuration Cloud Gateway
  cloud:
    gateway:
      # Discovery Locator (routage automatique via Eureka)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - name: RewritePath
              args:
                regexp: "'/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
      
      # Configuration globale CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            exposed-headers:
              - Authorization
            allow-credentials: true
            max-age: 3600
      
      # Configuration des routes par défaut
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,PUT,DELETE
            series: SERVER_ERROR
            exceptions: java.io.IOException,java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
        
        # Rate Limiting global
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 100 # tokens par seconde
              burstCapacity: 200 # capacité maximale
              requestedTokens: 1 # tokens par requête
  
  # Configuration Redis (pour rate limiting et cache)
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

  # Configuration Security (JWT validation directe via secret partagé)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:teranga-biz-platform}

# Configuration Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${HOSTNAME:api-gateway}
    non-secure-port: ${server.port:8080}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


# Configuration JWT (Même secret que user-service)
jwt:
  secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

# Configuration Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
    instances:
      user-service-circuit-breaker:
        base-config: default
      produits-circuit-breaker:
        base-config: default
      boutiques-circuit-breaker:
        base-config: default
      # ... autres microservices à ajouter selon besoin ...
      
  # Configuration des timeouts
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
    instances:
      user-service-circuit-breaker:
        timeoutDuration: 3s
      produits-circuit-breaker:
        timeoutDuration: 5s
      boutiques-circuit-breaker:
        timeoutDuration: 5s

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:production}

# Logs
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO